### ISSUE TITLE
import not found or unreadable: ../ember-freestyle/highlight.js/zenburn.

### ISSUE THREAD

**Issue by zidjian257** [chrislopresto/ember-freestyle#123]
When upgrading from 0.2.14 to 0.3.0 (and still with 0.4.0 or 0.4.1) im getting following error:

```
File: C:/projects/mvb-ember-ui-guides/tmp/sass_compiler-input_base_path-pJD3njA1.tmp/components/freestyle-notes.scss (12)
The Broccoli Plugin: [SassCompiler] failed with:
Error: File to import not found or unreadable: ../ember-freestyle/highlight.js/zenburn.
Parent style sheet: C:/projects/mvb-ember-ui-guides/tmp/sass_compiler-input_base_path-pJD3njA1.tmp/components/freestyle-notes.scss
    at options.error (C:\projects\mvb-ember-ui-guides\node_modules\ember-freestyle\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\node-sass\lib\index.js:291:26)

The broccoli plugin was instantiated at:
    at SassCompiler.Plugin (C:\projects\mvb-ember-ui-guides\node_modules\broccoli-plugin\index.js:7:31)
    at SassCompiler.CachingWriter [as constructor] (C:\projects\mvb-ember-ui-guides\node_modules\broccoli-caching-writer\index.js:18:10)
    at new SassCompiler (C:\projects\mvb-ember-ui-guides\node_modules\ember-freestyle\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\index.js:20:17)
    at C:\projects\mvb-ember-ui-guides\node_modules\ember-freestyle\node_modules\ember-cli-sass\index.js:38:12
    at Array.map (native)
    at SASSPlugin.toTree (C:\projects\mvb-ember-ui-guides\node_modules\ember-freestyle\node_modules\ember-cli-sass\index.js:35:34)
    at C:\projects\mvb-ember-ui-guides\node_modules\ember-cli-preprocess-registry\preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (C:\projects\mvb-ember-ui-guides\node_modules\ember-cli-preprocess-registry\preprocessors.js:178:11)
    at module.exports.preprocessCss (C:\projects\mvb-ember-ui-guides\node_modules\ember-cli-preprocess-registry\preprocessors.js:148:10)
```
Do you have an idea what could cause this issue

**Comment by zidjian257** [comment]
no unfortunatelly not - I'm staying with 0.2.14

**Comment by callovarne** [comment]
Were there a few spots missed in #111? To get my project building, I had to remove some highlight.js references in:
* [/addon/styles/components/freestyle-notes.scss](https://github.com/chrislopresto/ember-freestyle/blob/23dafc18360552bc9e25693a27193aea8a330fe0/addon/styles/components/freestyle-notes.scss#L12)
* [/addon/styles/components/freestyle-usage.scss](https://github.com/chrislopresto/ember-freestyle/blob/23dafc18360552bc9e25693a27193aea8a330fe0/addon/styles/components/freestyle-usage.scss#L36)

I don't know if it's the right fix, but it seemed odd to me that the imports stuck around after the shift to CDN.

**Comment by chrislopresto** [comment]
@callovarne Those imports were intentional. During the addon build, we were still pulling in highlight.js CSS files, renaming them to SCSS, and importing them within modifier selectors as a means of supporting themes on individual `freestyle-usage` or `freestyle-notes` instances.

That said, I think this is more trouble than it's worth, so I'm removing this in https://github.com/chrislopresto/ember-freestyle/pull/129. Most people probably want a single theme anyway.

**Comment by chrislopresto** [comment]
@zidjian257 @rajasegar @callovarne Whenever you have a chance, can you let me know if the changes in v0.5.0 and v0.6.0 fix things up for you? Cheers!
