### ISSUE TITLE
TypeError: Cannot set property '_directoryPath' of undefined

### ISSUE THREAD

**Issue by ming-codes** [chrislopresto/ember-freestyle#125]
```
TypeError: Cannot set property '_directoryPath' of undefined
    at Directory (/Users/mingliu/Workspace/prime/node_modules/broccoli-source/index.js:6:23)
    at UnwatchedDir (/Users/mingliu/Workspace/prime/node_modules/broccoli-source/index.js:65:13)
    at Class.treeForAddonStyles (/Users/mingliu/Workspace/prime/node_modules/ember-freestyle/index.js:56:38)
```

Apparently `unwatchedTree` needs to be invoked as a constructor.

**Comment by Kerrick** [comment]
This is related to https://github.com/rwjblue/broccoli-unwatched-tree/issues/4
