### ISSUE TITLE
Issues with installing new version of ember-freestyle

### ISSUE THREAD

**Issue by tarikEast** [chrislopresto/ember-freestyle#131]
Hi, today I tried to install new ember-freestyle to replace my forked ember-freestyle version in project, but I got this when trying to install it.

```
ember install ember-freestyle
Path must be a string. Received null
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at CoreObject.<anonymous> (/usr/lib/node_modules/ember-cli/lib/models/addon-discovery.js:117:26)
    at Array.map (native)
    at CoreObject.discoverFromDependencies (/usr/lib/node_modules/ember-cli/lib/models/addon-discovery.js:107:70)
    at CoreObject.discoverChildAddons (/usr/lib/node_modules/ember-cli/lib/models/addon-discovery.js:69:33)
    at CoreObject.discoverAddons (/usr/lib/node_modules/ember-cli/lib/models/addon.js:218:42)
    at CoreObject.initializeAddons (/usr/lib/node_modules/ember-cli/lib/models/addon.js:231:10)
    at setupRegistryForEachAddon (/usr/lib/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:18:10)
    at Object.module.exports.setupRegistry (/usr/lib/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:46:3)
```
I have cleaned the npm cache and removed node_modules

**Comment by tarikEast** [comment]
Additional information: I managed to install it on our ember project, but couldn't do the same on ember addon. Ember cli version is 2.8 on addon. Is it possible that that I need greater version of ember (on project is 2.9.1)

**Comment by chrislopresto** [comment]
@tarikEast I have https://github.com/chrislopresto/ember-freestyle-test-addon for testing Ember Freestyle within an addon. The addon is currently in good shape, pulling in Ember Freestyle 0.6.0, building with Ember CLI 2.13.

Upgrading Ember CLI would be worth a shot. I'm not intimately familiar with the changeset between 2.8 and 2.13. Another option would be to fork ember-freestyle-test-addon to try to create a clean repro of your issue.

**Comment by tarikEast** [comment]
Will try to make reproduce on fork and will get back to you

**Comment by chrislopresto** [comment]
Sorry, I didn't read this closely enough. The generator isn't working, which is also reported in #132 

Ok. I'll take a look at this sometime this week. In the meantime, a manual install should work just fine.

**Comment by chrislopresto** [comment]
Just an update... I tried unsuccessfully to reproduce this. I am still able to run `ember install ember-freestyle` just fine locally using Ember CLI 2.13.

I'm going to close this for now. @tarikEast, please reopen if you're still having problems or tips for reproducing.
