### ISSUE TITLE
After recent yarn install, ember project will not build

### ISSUE THREAD

**Issue by alexmiddeleer** [chrislopresto/ember-freestyle#183]
This started happening this morning, before any code changes (including to dependencies), but after running yarn. Uninstalling ember-freestyle fixes the build. I suspect one of ember-freestyle's dependencies was updated and the update contained a regression? I am happy to provide any other info if it can help debug the issue. I tried clearing my yarn cache and `rm -rf node_modules` and `tmp`, all of the usual tactics that I'm aware of.

```

=================================================================================

ENV Summary:

  TIME: Mon Jul 23 2018 11:37:20 GMT-0400 (EDT)
  TITLE: ember
  ARGV:
  - /Users/alex/.nvm/versions/node/v6.9.0/bin/node
  - /usr/local/bin/ember
  - test
  - -s
  - --launch
  - Chrome
  EXEC_PATH: /Users/alex/.nvm/versions/node/v6.9.0/bin/node
  TMPDIR: /var/folders/x0/c5k5kgt171xcffrn39lsk69c0000gn/T
  SHELL: /bin/bash
  PATH:
  - /Users/alex/.nvm/versions/node/v6.9.0/bin
  - /Users/alex/.rvm/gems/ruby-2.1.2/bin
  - /Users/alex/.rvm/gems/ruby-2.1.2@global/bin
  - /Users/alex/.rvm/rubies/ruby-2.1.2/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Users/alex/.rvm/bin
  - /usr/local/Cellar/mysql55/5.5.49/bin
  - /Users/alex/scripts
  - /Users/alex/.rvm/bin
  - /usr/local/opt/fzf/bin
  - /Users/alex/.rvm/bin
  PLATFORM: darwin x64
  FREEMEM: 3320086528
  TOTALMEM: 17179869184
  UPTIME: 973
  LOADAVG: 2.36865234375,2.8291015625,2.8203125
  CPUS:
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - http_parser: 2.7.0
  - icu: 57.1
  - modules: 48
  - node: 6.9.0
  - openssl: 1.0.2j
  - uv: 1.9.1
  - v8: 5.1.281.84
  - zlib: 1.2.8

ERROR Summary:

  - broccoliBuilderErrorStack: Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at /Users/alex/proj/mobile-fe/node_modules/ember-freestyle/freestyle-usage-snippet-finder.js:115:67
    at Array.forEach (native)
    at /Users/alex/proj/mobile-fe/node_modules/ember-freestyle/freestyle-usage-snippet-finder.js:114:11
    at tryCatch (/Users/alex/proj/mobile-fe/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/alex/proj/mobile-fe/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/alex/proj/mobile-fe/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/alex/proj/mobile-fe/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  - codeFrame: EISDIR: illegal operation on a directory, read
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `SnippetFinder` plugin. 💥
EISDIR: illegal operation on a directory, read
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `SnippetFinder` plugin. 💥
EISDIR: illegal operation on a directory, read
  - name: Error
  - nodeAnnotation: SnippetFinder
  - nodeName: SnippetFinder
  - originalErrorMessage: EISDIR: illegal operation on a directory, read
  - stack: Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at /Users/alex/proj/mobile-fe/node_modules/ember-freestyle/freestyle-usage-snippet-finder.js:115:67
    at Array.forEach (native)
    at /Users/alex/proj/mobile-fe/node_modules/ember-freestyle/freestyle-usage-snippet-finder.js:114:11
    at tryCatch (/Users/alex/proj/mobile-fe/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/alex/proj/mobile-fe/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/alex/proj/mobile-fe/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/alex/proj/mobile-fe/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

=================================================================================
```

**Comment by lukemelia** [comment]
I've not been able to reproduce this. Are you still experiencing this issue @alexmiddeleer ?

**Comment by alexmiddeleer** [comment]
No, it stopped happening - I never had time to debug unfortunately.
