### ISSUE TITLE
The Broccoli Plugin: [BroccoliMergeTrees] failed with:

### ISSUE THREAD

**Issue by oligriffiths** [chrislopresto/ember-freestyle#20]
Hey

I know this is WIP but I wonder if you could help me with the following error I get after running `ember serve` after installing the addon:

```
Error: Merge error: file app/styles/app.scss exists in /Users/oli/Projects/emblr/tmp/broccoli_merge_trees-input_base_path-lqYGewTa.tmp/19 and /Users/oli/Projects/emblr/tmp/broccoli_merge_trees-input_base_path-lqYGewTa.tmp/25
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
    at BroccoliMergeTrees._mergeRelativePath (/Users/oli/Projects/emblr/node_modules/broccoli-merge-trees/index.js:212:17)
    at BroccoliMergeTrees._mergeRelativePath (/Users/oli/Projects/emblr/node_modules/broccoli-merge-trees/index.js:238:31)
    at BroccoliMergeTrees._mergeRelativePath (/Users/oli/Projects/emblr/node_modules/broccoli-merge-trees/index.js:238:31)
    at BroccoliMergeTrees.build (/Users/oli/Projects/emblr/node_modules/broccoli-merge-trees/index.js:50:24)
    at /Users/oli/Projects/emblr/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/oli/Projects/emblr/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/oli/Projects/emblr/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/oli/Projects/emblr/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/oli/Projects/emblr/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/oli/Projects/emblr/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/oli/Projects/emblr/node_modules/broccoli-merge-trees/index.js:29:10)
    at BroccoliMergeTrees (/Users/oli/Projects/emblr/node_modules/broccoli-merge-trees/index.js:23:53)
    at mergeTrees (/Users/oli/Projects/emblr/node_modules/ember-component-css/index.js:19:16)
    at EmberApp.styles (/Users/oli/Projects/emblr/node_modules/ember-component-css/index.js:76:27)
    at EmberApp.toArray (/Users/oli/Projects/emblr/node_modules/ember-cli/lib/broccoli/ember-app.js:1543:10)
    at EmberApp.toTree (/Users/oli/Projects/emblr/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:30)
    at module.exports (/Users/oli/Projects/emblr/ember-cli-build.js:23:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/oli/Projects/emblr/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/oli/Projects/emblr/node_modules/ember-cli/lib/models/builder.js:89:10)
```

package.json:
```
"devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "broccoli-sass": "^0.7.0",
    "ember-ajax": "0.7.1",
    "ember-body-class": "0.3.8",
    "ember-cli": "2.4.2",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-bourbon": "^1.2.1",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.2.1",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-component-css": "0.1.7",
    "ember-data": "^2.4.0",
    "ember-data-filter": "^1.13.0",
    "ember-data-has-many-query": "0.0.4",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-freestyle": "0.2.7",
    "ember-load-initializers": "^0.5.0",
    "ember-resolver": "^2.0.3",
    "ember-truth-helpers": "^1.2.0",
    "loader.js": "^4.0.0"
  }
```
bower.json:
```
"dependencies": {
    "ember": "2.4",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-qunit-notifications": "0.1.0",
    "bourbon": "4.2.6",
    "remarkable": "1.6.2",
    "highlightjs": "9.1.0"
  }
```

Thanks

**Comment by oligriffiths** [comment]
Seems as though the problem is with `broccoli-sass`

**Comment by jakehow** [comment]
@oligriffiths for now you need to do `rm node_modules/ember-freestyle/app/styles/app.scss`

There are a couple of other projects that have dealt with this, some remove it in a pre-publish script.

**Comment by chrislopresto** [comment]
Seems like this problem came from elsewhere. Hopefully it's no longer plaguing folks. I'm going to close this for now. Feel free to reopen if necessary.
