### ISSUE TITLE
The package handlebars@4.0.5 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by robabby** [chrislopresto/ember-freestyle#39]
Hey!  I loved your emberconf talk and am looking forward to trying out this addon.  Unfortunately I am getting the following error when I run `ember install ember-freestyle`.  Any thoughts?

```
The package handlebars@4.0.5 does not satisfy its siblings' peerDependencies requirements!
Error: The package handlebars@4.0.5 does not satisfy its siblings' peerDependencies requirements!
    at /Users/rob/Workbench/savo-styleguide/node_modules/npm/lib/install.js:125:32
    at /Users/rob/Workbench/savo-styleguide/node_modules/npm/lib/install.js:268:7
    at /Users/rob/Workbench/savo-styleguide/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
    at /Users/rob/Workbench/savo-styleguide/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/Users/rob/Workbench/savo-styleguide/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /Users/rob/Workbench/savo-styleguide/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/Users/rob/Workbench/savo-styleguide/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /Users/rob/Workbench/savo-styleguide/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/Users/rob/Workbench/savo-styleguide/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /Users/rob/Workbench/savo-styleguide/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
```

**Comment by robabby** [comment]
Just attempted this again and everything completed successfully.  There must have been an issue somewhere in the dependency tree.

**Comment by chrislopresto** [comment]
Glad to hear it!
